process.env.SUPABASE_URL ||= 'https://x.supabase.co'; process.env.SUPABASE_SERVICE_ROLE_KEY ||= 'x'; process.env.OPENAI_API_KEY ||= 'x';
process.env.NO_PROXY = '127.0.0.1,localhost'; process.env.no_proxy = '127.0.0.1,localhost';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import os from 'node:os'; import path from 'node:path';
const { probeUrl, downloadMedia } = await import('../src/ytdlp.js');
const { probeMedia } = await import('../src/ffmpeg.js');
const url = 'http://127.0.0.1:8765/clip.mp4';
const meta = await probeUrl(url);
console.log('meta', meta);
const dir = mkdtempSync(path.join(os.tmpdir(), 'dl-'));
const pct: number[] = [];
const f = await downloadMedia(url, dir, { kind: 'video', quality: 720 }, (p) => pct.push(p));
console.log('video ->', f, (await probeMedia(f)).duration);
const dir2 = mkdtempSync(path.join(os.tmpdir(), 'dl-'));
const a = await downloadMedia(url, dir2, { kind: 'audio', audioFormat: 'mp3' }, () => {});
console.log('mp3 ->', a); assert.ok(a.endsWith('.mp3'));
const dir3 = mkdtempSync(path.join(os.tmpdir(), 'dl-'));
const raw = await downloadMedia(url, dir3, { kind: 'audio', audioFormat: 'raw' }, () => {});
console.log('raw ->', raw, (await probeMedia(raw)).hasAudio);
console.log('YTDLP LOCAL PIPELINE OK');
